FROM apache/airflow:2.9.2-python3.11

# Switch to root user to perform installation tasks
USER root

# Copy the requirements file
COPY ./requirements.txt /

# Update the package list and install necessary packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    openjdk-17-jdk \
    build-essential \
    libkrb5-dev \
    procps \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set environment variable for Java home
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

# Set environment variable for Airflow user ID
ENV AIRFLOW_UID=50000

# Switch back to the airflow user
USER airflow

# Install Python dependencies
RUN pip install --no-cache-dir -r /requirements.txt
